import type { Product } from '@shared/types';
export const MOCK_PRODUCTS: Product[] = [
  {
    id: 'prod_01',
    name: 'Organic Hass Avocados',
    description: 'Creamy and delicious Hass avocados, grown using sustainable organic farming methods. Perfect for toast, salads, and guacamole.',
    price: 2.50,
    imageUrl: 'https://images.unsplash.com/photo-1523049673857-eb18f1d7b578?q=80&w=800&auto=format&fit=crop',
    sellerName: 'Green Valley Farms',
    category: 'Fruits',
  },
  {
    id: 'prod_02',
    name: 'Heirloom Tomatoes',
    description: 'A vibrant mix of juicy, flavorful heirloom tomatoes. Bursting with sweet, complex flavors that supermarket tomatoes can\'t match.',
    price: 4.99,
    imageUrl: 'https://images.unsplash.com/photo-1561138233-f39a5b55a3c5?q=80&w=800&auto=format&fit=crop',
    sellerName: 'Sunset Orchards',
    category: 'Vegetables',
  },
  {
    id: 'prod_03',
    name: 'Artisanal Sourdough Bread',
    description: 'Handcrafted sourdough bread with a crispy crust and a soft, chewy interior. Made with locally milled flour and a natural starter.',
    price: 6.00,
    imageUrl: 'https://images.unsplash.com/photo-1533087353484-52a73b35331a?q=80&w=800&auto=format&fit=crop',
    sellerName: 'The Daily Rise Bakery',
    category: 'Bakery',
  },
  {
    id: 'prod_04',
    name: 'Free-Range Eggs',
    description: 'A dozen large brown eggs from happy, free-range chickens. Rich, golden yolks and exceptional taste.',
    price: 5.50,
    imageUrl: 'https://images.unsplash.com/photo-1598965775222-384911325b1a?q=80&w=800&auto=format&fit=crop',
    sellerName: 'Happy Hen Homestead',
    category: 'Dairy & Eggs',
  },
  {
    id: 'prod_05',
    name: 'Raw Wildflower Honey',
    description: 'Unfiltered and unpasteurized raw honey from wildflowers. A sweet, floral taste of nature in a jar.',
    price: 12.00,
    imageUrl: 'https://images.unsplash.com/photo-1558642452-9d2a7deb7f62?q=80&w=800&auto=format&fit=crop',
    sellerName: 'Golden Comb Apiary',
    category: 'Pantry',
  },
  {
    id: 'prod_06',
    name: 'Gourmet Mushroom Mix',
    description: 'A curated selection of fresh gourmet mushrooms, including shiitake, oyster, and cremini. Perfect for sautés, soups, and pasta.',
    price: 9.75,
    imageUrl: 'https://images.unsplash.com/photo-1528504923492-8c22421c39a4?q=80&w=800&auto=format&fit=crop',
    sellerName: 'Fungi Friends Co.',
    category: 'Vegetables',
  },
  {
    id: 'prod_07',
    name: 'Freshly Roasted Coffee Beans',
    description: 'Single-origin Arabica coffee beans, roasted to perfection. Notes of chocolate, citrus, and caramel.',
    price: 18.50,
    imageUrl: 'https://images.unsplash.com/photo-1511920183353-3c7c95a5742c?q=80&w=800&auto=format&fit=crop',
    sellerName: 'Morning Ritual Roasters',
    category: 'Pantry',
  },
  {
    id: 'prod_08',
    name: 'Sweet Corn on the Cob',
    description: 'Four ears of sweet, tender corn, picked at the peak of freshness. Ideal for grilling, boiling, or roasting.',
    price: 3.00,
    imageUrl: 'https://images.unsplash.com/photo-1598164074852-36b745f586e3?q=80&w=800&auto=format&fit=crop',
    sellerName: 'Green Valley Farms',
    category: 'Vegetables',
  },
];